package http

import (
	"io"
	"slices"
	"strconv"
	"strings"

	"github.com/aarock1234/fphttp/httptrace"
)

// writeOrderedHeaders includes fields generated by the transport in the same
// ordering as caller-supplied fields. Framing values come from transferWriter,
// rather than the request's Header map, to preserve HTTP message boundaries.
func (r *Request) writeOrderedHeaders(w io.Writer, tw *transferWriter, host string, extra Header, order []string, trace *httptrace.ClientTrace) error {
	headers := make(Header, len(r.Header)+len(extra)+4)

	for name, values := range r.Header {
		name = CanonicalHeaderKey(name)
		if !reqWriteExcludeHeader[name] {
			headers[name] = append(headers[name], values...)
		}
	}

	headers["Host"] = []string{host}
	userAgent := defaultUserAgent
	if r.Header.has("User-Agent") {
		userAgent = r.Header.Get("User-Agent")
	}
	if userAgent != "" {
		headers["User-Agent"] = []string{userAgent}
	}

	if err := tw.addFramingHeaders(headers); err != nil {
		return err
	}
	for name, values := range extra {
		name = CanonicalHeaderKey(name)
		headers[name] = append(headers[name], values...)
	}

	return headers.writeSubsetOrdered(w, nil, order, trace)
}

func (t *transferWriter) addFramingHeaders(headers Header) error {
	if t.Close && !hasToken(t.Header.get("Connection"), "close") {
		headers["Connection"] = append([]string{"close"}, headers["Connection"]...)
	}

	if t.shouldSendContentLength() {
		headers["Content-Length"] = []string{strconv.FormatInt(t.ContentLength, 10)}
	} else if chunked(t.TransferEncoding) {
		headers["Transfer-Encoding"] = []string{"chunked"}
	}

	keys, err := trailerHeaderKeys(t.Trailer)
	if err != nil {
		return err
	}
	if len(keys) > 0 {
		headers["Trailer"] = []string{strings.Join(keys, ",")}
	}

	return nil
}

func trailerHeaderKeys(trailer Header) ([]string, error) {
	keys := make([]string, 0, len(trailer))
	for name := range trailer {
		name = CanonicalHeaderKey(name)
		switch name {
		case "Transfer-Encoding", "Trailer", "Content-Length":
			return nil, badStringError("invalid Trailer key", name)
		}
		keys = append(keys, name)
	}
	slices.Sort(keys)

	return keys, nil
}
